#!/usr/bin/env bash

# Add an "alert" alias for long running commands.  Use like so:
#   sleep 10; alert
alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'

if hash doas 2>/dev/null; then
    # Use doas instead of sudo
    alias sudo='doas'
else
    # Enable aliases for Sudo commands
    alias sudo='sudo '
fi

alias makepkg='makepkg -si'

alias nano='nano -c'
alias snano='sudo nano'
alias svim='sudo vim'

alias vfm='vifmrun'

if hash eza 2>/dev/null; then
    alias eza='eza --icons --group-directories-first'
    alias ls='eza'                      # add file type extensions
    alias la='ls -ah'                   # show hidden files
    alias ll='ls -alg'                  # long listing format
    alias tree='eza --tree'             # tree listing
    alias treed='tree --only-dirs'      # tree listing directories
else
    alias ls='ls -Fh --color=always'    # add colors and file type extensions
    alias la='ls -Ah'                   # show hidden files
    alias ll='ls -als'                  # long listing format
    alias tree='tree -CAhF --dirsfirst' # tree listing
    alias treed='tree -CAFd'            # tree listing directories
fi
alias llf="\ls -l | egrep -v '^d'"      # long list files only
alias lld="\ls -l | egrep '^d'"         # long list directories only

alias ~='cd ~'
alias cd..='cd ..'
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias .....='cd ../../../..'

# cd back into the previous directory
alias bd='cd "$OLDPWD"'

# Make directories recursively
alias mkdir='mkdir -p'

# Create and go to the directory
function mkdirg() {
    mkdir -p $1
    cd $1
}

alias cpr="rsync --archive -hh --partial --info=stats1,progress2 --modify-window=1"
alias mvr="rsync --archive -hh --partial --info=stats1,progress2 --modify-window=1 --remove-source-files"

alias scpr="sudo rsync --archive -hh --partial --info=stats1,progress2 --modify-window=1 --rsync-path='sudo rsync'"
alias smvr="sudo rsync --archive -hh --partial --info=stats1,progress2 --modify-window=1 --rsync-path='sudo rsync' --remove-source-files"

function cpp() {
    set -e
    strace -q -ewrite cp -- "${1}" "${2}" 2>&1 |
        awk '{
    count += $NF
    if (count % 10 == 0) {
        percent = count / total_size * 100
        printf "%3d%% [", percent
        for (i=0;i<=percent;i++)
            printf "="
            printf ">"
            for (i=percent;i<100;i++)
                printf " "
                printf "]\r"
            }
        }
    END { print "" }' total_size=$(stat -c '%s' "${1}") count=0
}

# Less
alias less='less -iRJ --use-color'

# Grep
alias grep='grep --colour=auto'
alias sgrep='grep -R -n -H -C 5 --exclude-dir={.git,.svn,CVS} '

# Search files in the current folder
alias f="find . | grep "
alias ff='find . -type f -name'
alias fd='find . -type d -name'

# Count all files (recursively) in the current folder
alias countfiles="for t in files links directories; do echo \`find . -type \${t:0:1} | wc -l\` \$t; done 2> /dev/null"

# Searches for text in all files in the current folder
function ftext() {
    # -i case-insensitive
    # -I ignore binary files
    # -H causes filename to be printed
    # -r recursive search
    # -n causes line number to be printed
    # optional: -F treat search term as a literal, not a regular expression
    # optional: -l only print filenames and not the matching lines ex. grep -irl "$1" *
    grep -iIHrn --color=always "$1" . | less -r
}

# Start ArchiSteamFarm
if [[ -d "$HOME/.local/bin/asf" ]]; then
    alias asf="$HOME/.local/bin/asf/ArchiSteamFarm"
fi

# Update Proton
alias update-proton="$GIT_DIRECTORY/../SystemSoftware/ProtonUpdater/cproton.sh"

# Setup extra password store
alias pay="PASSWORD_STORE_DIR=$XDG_DATA_HOME/pass-pay pass"

alias bi="beet import"
alias bsi="beet -s import"

alias open="xdg-open"
alias copy="wl-copy"

alias pman='sudo pacman'
# alias pman-mirrors-update='sudo pacman-mirrors --geoip'
alias pman-orphans-clean='sudo pacman -Rs $(pacman -Qtdq)'
alias pman-orphans-fullclean='sudo pacman -Rns $(pacman -Qtdq)'
# fzf
alias pman-browse="pacman -Slq | fzf --multi --preview 'pacman -Si {1}' | xargs -ro sudo pacman -S"
alias pman-list="pacman -Qq | fzf --multi --preview 'pacman -Qi {1}' | xargs -ro sudo pacman -Rcs"

function pman-update-mirrors() {
    country="$1" # US
    curl -s "https://archlinux.org/mirrorlist/?country=$country&protocol=https&use_mirror_status=on" |
        sed -e 's/#Server/Server/' -e '/^## \w*$/d' |
        rankmirrors - > /tmp/mirrorlist
    sudo cp /tmp/mirrorlist /etc/pacman.d/mirrorlist
}

# Alias's to show disk space and space used in a folder
alias diskspace="du -S | sort -n -r |more"
alias folders='du -h --max-depth=1'
alias folderssort='find . -maxdepth 1 -type d -print0 | xargs -0 du -sk | sort -rn'
alias mountedinfo='df -hT'

# Audio Outout info
alias aoutput='cat /proc/asound/card2/pcm0p/sub0/hw_params'

# Search running processes
# alias p="ps aux | grep "
alias topcpu="/bin/ps -eo pcpu,pid,user,args | sort -k 1 -r | head -10"

# Show all logs in /var/log
alias logs="sudo find /var/log -type f -exec file {} \; | grep 'text' | cut -d' ' -f1 | sed -e's/:$//g' | grep -v '[0-9]$' | xargs tail -f"

# Show used DNS addresses
alias dnsview='cat /etc/resolv.conf'

# Show current network connections to the server
alias ipview="netstat -anpl | grep :80 | awk {'print \$5'} | cut -d\":\" -f1 | sort | uniq -c | sort -n | sed -e 's/^ *//' -e 's/ *\$//'"

# Show open ports
alias openports='netstat -nape --inet'

alias sys='systemctl'
alias use='systemctl --user'

alias or='ollama run'
alias ops='ollama ps'
alias ols='ollama list'

# Extend screen
alias extendtolaptop='ssh -YC amadeus x2x -east -to :0.0'

# occ for nextcloud container
alias occ='ssh amadeus "docker exec -i --user www-data nextcloud-app php occ"'

# transmission
alias t='transmission-remote amadeus:9091 --authenv'

# docker
alias dstat='docker stats'
alias dls='docker container ls --format "table {{.ID}}\t{{.RunningFor}}\t{{.Status}}\t{{.Names}}\t{{.Networks}}"'
alias dll='docker container ls --all --format "table {{.ID}}\t{{.Image}}\t{{.RunningFor}}\t{{.State}}\t{{.Status}}\t{{.Names}}\t{{.Networks}}"'
alias dup='docker-compose up -d'
alias dupo='docker-compose up -d --remove-orphans'
alias ddown='docker-compose down'
alias dstop='docker-compose stop'
alias dlog='docker logs'
alias dx='docker exec -it'

alias gs="git fetch && git status"
alias gc="git commit"
alias gp="git push"
alias gf="git fetch --prune"
alias gF="git pull"
alias gd="git diff"
alias glog="git log --oneline"
alias glogl="git log --show-signature"

bare_git_dir="$GIT_DIRECTORY/private-Dotfiles/"
bare_work_tree="$HOME"

alias gprivate="git --git-dir=$bare_git_dir --work-tree=$bare_work_tree"
alias gsprivate="gprivate fetch && gprivate status"
alias gcprivate="gprivate commit"
alias gpprivate="gprivate push"
alias gfprivate="gprivate pull"
alias gdprivate="gprivate diff"

alias pgs="pass git status"
alias pgp="pass git push"
alias pgf="pass git pull"
alias pgl="pass git log --oneline"

alias mpvt='mpv -vo tct'
alias shazam='songrec recognize'

alias ytdv='yt-dlp'
alias ytda='yt-dlp --config-locations ~/.config/yt-dlp/audio.conf'

function yta() {
    mpv --ytdl-format=bestaudio ytdl://ytsearch:"$*"
}

function ytv() {
    mpv ytdl://ytsearch:"$*"
}

function ex() {
    for archive in $*; do
        if [ -f $archive ]; then
            case $archive in
                *.tar.bz2) tar xvjf $archive ;;
                *.tar.gz) tar xvzf $archive ;;
                *.bz2) bunzip2 $archive ;;
                *.rar) rar x $archive ;;
                *.gz) gunzip $archive ;;
                *.tar) tar xvf $archive ;;
                *.tbz2) tar xvjf $archive ;;
                *.tgz) tar xvzf $archive ;;
                *.zip) unzip $archive ;;
                *.Z) uncompress $archive ;;
                *.7z) 7z x $archive ;;
                *) echo "don't know how to extract '$archive'..." ;;
            esac
        else echo "'$archive' is not a valid file!"
        fi
    done
}

alias ledger="ledger --init-file $XDG_CONFIG_HOME/ledger/ledgerrc"
alias mbsync="mbsync -c $XDG_CONFIG_HOME/isync/mbsyncrc"
