#+title:       Rofi
#+author:      Artem Smaznov
#+description: Window switcher, run dialog, ssh-launcher and dmenu replacement
#+startup:     overview
#+property:    header-args :tangle ~/.config/rofi/config.rasi
#+auto_tangle: t

* Table of Contents :toc:
- [[#dependencies][Dependencies]]
- [[#configuration][Configuration]]
- [[#list-view][List View]]
- [[#imports][Imports]]
- [[#keybindings][Keybindings]]
  - [[#typing][Typing]]
  - [[#navigation][Navigation]]
  - [[#misc][Misc]]
  - [[#custom][Custom]]
  - [[#mouse-bindings][Mouse Bindings]]
- [[#rofi-pass][Rofi-Pass]]
  - [[#main][Main]]
  - [[#programs-to-be-used][Programs to be used]]
  - [[#misc-settings][Misc settings]]
  - [[#options-for-generating-new-password-entries][Options for generating new password entries]]
  - [[#keybindings-1][Keybindings]]

* Dependencies
|------+-------------|
| Name | Description |
|------+-------------|
| [[https://archlinux.org/packages/?name=rofi][rofi]] | Run dialog  |
|------+-------------|

#+begin_example shell
sudo pacman -S rofi
#+end_example

* Configuration
#+begin_src conf
configuration {
  monitor:                        "primary";
  modi: "window,run,drun,ssh,keys";
	font: "Hack Nerd Font 12";
/*	location: 0;*/
/*	padding: 5;*/
/*	yoffset: 0;*/
/*	xoffset: 0;*/
/*	fixed-num-lines: true;*/
  show-icons: true;
  terminal: "alacritty";
/*	ssh-client: "ssh";*/
/*	ssh-command: "{terminal} -e {ssh-client} {host} [-p {port}]";*/
/*	run-command: "{cmd}";*/
/*	run-list-command: "";*/
/*	run-shell-command: "{terminal} -e {cmd}";*/
/*	window-command: "wmctrl -i -R {window}";*/
/*	window-match-fields: "all";*/
  icon-theme: "Papirus" ;
/*	drun-match-fields: "name,generic,exec,categories,keywords";*/
/*	drun-categories: ;*/
/*	drun-show-actions: false;*/
/*	drun-display-format: "{name} [<span weight='light' size='small'><i>({generic})</i></span>]";*/
  disable-history: false;
/*	ignored-prefixes: "";*/
/*	sort: false;*/
/*	sorting-method: "normal";*/
  case-sensitive: false;
/*	cycle: true;*/
/*	sidebar-mode: false;*/
/*	eh: 1;*/
/*	auto-select: false;*/
/*	parse-hosts: false;*/
/*	parse-known-hosts: true;*/
/*	combi-modi: "window,run";*/
/*	matching: "normal";*/
/*	tokenize: true;*/
/*	m: "-5";*/
/*	line-margin: 2;*/
/*	line-padding: 1;*/
/*	filter: ;*/
/*	separator-style: "dash";*/
/*	hide-scrollbar: false;*/
/*	fullscreen: false;*/
/*	fake-transparency: false;*/
/*	dpi: -1;*/
/*	threads: 0;*/
/*	scrollbar-width: 8;*/
/*	scroll-method: 0;*/
/*	fake-background: "screenshot";*/
/*	window-format: "{w}    {c}   {t}";*/
  click-to-exit: true;
/*	show-match: true;*/
/*  theme: "gruvbox-dark";*/
/*	color-normal: ;*/
/*	color-urgent: ;*/
/*	color-active: ;*/
/*	color-window: ;*/
/*	max-history-size: 25;*/
/*	combi-hide-mode-prefix: false;*/
/*	matching-negate-char: '-' /* unsupported */;*/
/*	cache-dir: ;*/
/*	window-thumbnail: false;*/
/*	drun-use-desktop-cache: false;*/
/*	drun-reload-desktop-cache: false;*/
/*	pid: "/run/user/1000/rofi.pid";*/
/*	display-window: ;*/
/*	display-windowcd: ;*/
/*	display-run: ;*/
/*	display-ssh: ;*/
/*	display-drun: ;*/
/*	display-combi: ;*/
/*	display-keys: ;*/
}
#+end_src

* List View
#+begin_src conf
listview {
  columns: 2;
}
#+end_src

* Imports
#+begin_src conf
@import "keys.rasi"
@import "themes/base16.rasi"
#+end_src

* Keybindings
:properties:
:header-args: :tangle keys.rasi
:end:
=Shift+Tab= is set with =ISO_Left_Tab=
#+begin_src conf
configuration {
#+end_src
** Typing
#+begin_src conf
/*	kb-clear-line:              "Control+w";*/
/*	kb-remove-word-back:        "Control+Alt+h,Control+BackSpace";*/
/*	kb-remove-word-forward:     "Control+Alt+d";*/
/*	kb-remove-char-forward:     "Delete,Control+d";*/
/*	kb-remove-char-back:        "BackSpace,Shift+BackSpace,Control+h";*/
kb-remove-char-back:            "BackSpace";
kb-remove-to-eol:               "Control+Shift+e";
kb-remove-to-sol:               "Control+u";
#+end_src

** Navigation
#+begin_src conf
/*	kb-move-front:              "Control+a";*/
/*	kb-move-end:                "Control+e";*/
/*	kb-move-word-back:          "Alt+b,Control+Left";*/
/*	kb-move-word-forward:       "Alt+f,Control+Right";*/
/*	kb-move-char-back:          "Left,Control+b";*/
/*	kb-move-char-forward:       "Right,Control+f";*/
kb-row-left:                    "Control+Page_Up,Control+h";
kb-row-right:                   "Control+Page_Down,Control+l";
kb-row-up:                      "Up,Control+k,Control+p";
kb-row-down:                    "Down,Control+j,Control+n";
/*	kb-row-tab:                 "Tab";*/
/*	kb-page-prev:               "Page_Up";*/
/*	kb-page-next:               "Page_Down";*/
/*	kb-row-first:               "Home,KP_Home";*/
/*	kb-row-last:                "End,KP_End";*/
/*	kb-row-select:              "Control+space";*/

kb-accept-entry:                "Control+m,Return,KP_Enter";
/*	kb-accept-custom:           "Control+Return";*/
/*	kb-accept-alt:              "Shift+Return";*/
/*	kb-delete-entry:            "Shift+Delete";*/
#+end_src

** Misc
#+begin_src conf
kb-mode-complete:               "Control+L";
kb-primary-paste:               "Control+V,Shift+Insert";
kb-secondary-paste:             "Control+v,Insert";
kb-mode-next:                   "Shift+Right,Control+Tab";
kb-mode-previous:               "Shift+Left,Control+ISO_Left_Tab";
/*	kb-screenshot:              "Alt+S";*/
/*	kb-ellipsize:               "Alt+period";*/
/*	kb-toggle-case-sensitivity: "grave,dead_grave";*/
/*	kb-toggle-sort:             "Alt+grave";*/
/*	kb-cancel:                  "Escape,Control+g,Control+bracketleft";*/
#+end_src

** Custom
#+begin_src conf
/*	kb-custom-1:                "Alt+1";*/
/*	kb-custom-2:                "Alt+2";*/
/*	kb-custom-3:                "Alt+3";*/
/*	kb-custom-4:                "Alt+4";*/
/*	kb-custom-5:                "Alt+5";*/
/*	kb-custom-6:                "Alt+6";*/
/*	kb-custom-7:                "Alt+7";*/
/*	kb-custom-8:                "Alt+8";*/
/*	kb-custom-9:                "Alt+9";*/
/*	kb-custom-10:               "Alt+0";*/
/*	kb-custom-11:               "Alt+exclam";*/
/*	kb-custom-12:               "Alt+at";*/
/*	kb-custom-13:               "Alt+numbersign";*/
/*	kb-custom-14:               "Alt+dollar";*/
/*	kb-custom-15:               "Alt+percent";*/
/*	kb-custom-16:               "Alt+dead_circumflex";*/
/*	kb-custom-17:               "Alt+ampersand";*/
/*	kb-custom-18:               "Alt+asterisk";*/
/*	kb-custom-19:               "Alt+parenleft";*/
/*	kb-select-1:                "Super+1";*/
/*	kb-select-2:                "Super+2";*/
/*	kb-select-3:                "Super+3";*/
/*	kb-select-4:                "Super+4";*/
/*	kb-select-5:                "Super+5";*/
/*	kb-select-6:                "Super+6";*/
/*	kb-select-7:                "Super+7";*/
/*	kb-select-8:                "Super+8";*/
/*	kb-select-9:                "Super+9";*/
/*	kb-select-10:               "Super+0";*/
#+end_src

** Mouse Bindings
#+begin_src conf
/*	ml-row-left:                "ScrollLeft";*/
/*	ml-row-right:               "ScrollRight";*/
/*	ml-row-up:                  "ScrollUp";*/
/*	ml-row-down:                "ScrollDown";*/
/*	me-select-entry:            "MousePrimary";*/
/*	me-accept-entry:            "MouseDPrimary";*/
/*	me-accept-custom:           "Control+MouseDPrimary";*/
}
#+end_src

* Rofi-Pass
** Main
Permanently set alternative root dir. Use ":" to separate multiple roots which can be switched at runtime with =Control+Tab= and =Control+Shift+Tab=
#+begin_src conf :tangle ~/.config/rofi-pass/config
root=$XDG_DATA_HOME/pass:$XDG_DATA_HOME/pass-pay
#+end_src

rofi command. Make sure to have "$@" as last argument
#+begin_src conf :tangle ~/.config/rofi-pass/config
_rofi () {
    rofi -i -no-auto-select "$@"
}
#+end_src

default command to generate passwords
#+begin_src conf :tangle ~/.config/rofi-pass/config
_pwgen () {
	pwgen -y "$@"
}
#+end_src

image viewer to display qrcode of selected entry qrencode is needed to generate the image and a viewer that can read from pipes. Known viewers to work are feh and display
#+begin_src conf :tangle ~/.config/rofi-pass/config
_image_viewer () {
    feh -
#    display
}
#+end_src

xdotool needs the keyboard layout to be set using setxkbmap
You can do this in your autostart scripts (e.g. xinitrc)
If for some reason, you cannot do this, you can set the command here.
and set fix_layout to true
#+begin_src conf :tangle ~/.config/rofi-pass/config
fix_layout=false

layout_cmd () {
  setxkbmap us
}
#+end_src

fields to be used
#+begin_src conf :tangle ~/.config/rofi-pass/config
URL_field='url'
USERNAME_field='user'
AUTOTYPE_field='autotype'
#+end_src

delay to be used for :delay keyword
#+begin_src conf :tangle ~/.config/rofi-pass/config
delay=2
#+end_src

rofi-pass needs to close itself before it can type passwords. Set delay here.
#+begin_src conf :tangle ~/.config/rofi-pass/config
wait=0.2
#+end_src

delay between keypresses when typing (in ms)
#+begin_src conf :tangle ~/.config/rofi-pass/config
xdotool_delay=12
#+end_src

** Programs to be used
#+begin_src conf :tangle ~/.config/rofi-pass/config
EDITOR='vim'
BROWSER='xdg-open'
#+end_src

** Misc settings
#+begin_src conf :tangle ~/.config/rofi-pass/config
default_do='menu' # menu, autotype, copyPass, typeUser, typePass, copyUser, copyUrl, viewEntry, typeMenu, actionMenu, copyMenu, openUrl
auto_enter='false'
notify='false'
default_autotype='user :tab pass'
#+end_src

color of the help messages
leave empty for autodetection
#+begin_src conf :tangle ~/.config/rofi-pass/config
help_color="#4872FF"
#+end_src

Clipboard settings

Possible options: primary, clipboard, both
#+begin_src conf :tangle ~/.config/rofi-pass/config
clip=primary
#+end_src

Seconds before clearing pass from clipboard
#+begin_src conf :tangle ~/.config/rofi-pass/config
clip_clear=45
#+end_src

** Options for generating new password entries
open new password entries in editor
#+begin_src conf :tangle ~/.config/rofi-pass/config
edit_new_pass="true"
#+end_src

default_user is also used for password files that have no user field.
#+begin_src conf :tangle ~/.config/rofi-pass/config
#default_user="${ROFI_PASS_DEFAULT_USER-$(whoami)}"
#default_user2=mary_ann
#password_length=12
#+end_src

** Keybindings
#+begin_src conf :tangle ~/.config/rofi-pass/config
next_root="Control+Tab"
previous_root="Control+ISO_Left_Tab"
autotype="Alt+1"
type_user="Alt+2"
type_pass="Alt+3"
open_url="Alt+4"
copy_name="Alt+u"
copy_url="Alt+l"
copy_pass="Alt+p"
show="Alt+o"
copy_entry="Alt+2"
type_entry="Alt+1"
copy_menu="Alt+c"
action_menu="Alt+a"
type_menu="Alt+t"
help="Alt+h"
switch="Alt+x"
insert_pass="Alt+n"
#+end_src
