#+TITLE: MPV
#+AUTHOR: Artem Smaznov
#+DESCRIPTION: A vim-like minimalist media player
#+STARTUP: overview

* Table of Contents :toc:
- [[#dependencies][Dependencies]]
- [[#config][Config]]
  - [[#warning][Warning]]
  - [[#window][Window]]
  - [[#playback][Playback]]
  - [[#video][Video]]
  - [[#audio][Audio]]
  - [[#osd][OSD]]
  - [[#cache][Cache]]
  - [[#profiles][Profiles]]
  - [[#screenshot][Screenshot]]
  - [[#other][Other]]
- [[#scripts][Scripts]]
  - [[#torque-progress-bar][Torque Progress-bar]]
- [[#keybindings][Keybindings]]
  - [[#info][Info]]
  - [[#initialization][Initialization]]
  - [[#window-1][Window]]
  - [[#playback-1][Playback]]
  - [[#navigation][Navigation]]
  - [[#playlists][Playlists]]
  - [[#audio-1][Audio]]
  - [[#osd-1][OSD]]
  - [[#subtitles][Subtitles]]
  - [[#screenshot-1][Screenshot]]
  - [[#image-adjustment][Image Adjustment]]
  - [[#chapters][Chapters]]
  - [[#media-keys][Media Keys]]
  - [[#mouse-bindings][Mouse Bindings]]
  - [[#misc][Misc]]

* Dependencies
|---------------------+-------------------------------------|
| Name                | Description                         |
|---------------------+-------------------------------------|
| [[https://archlinux.org/packages/?name=mpv][mpv]]                 | A vim-like minimalist media player  |
| [[https://github.com/torque/mpv-progressbar][Torgue Progress-bar]] | Script for a different progress bar |
|---------------------+-------------------------------------|

#+begin_example shell
sudo pacman -S mpv
#+end_example

* Config
** Warning
The commented example options usually do _not_ set the default values. Call mpv with --list-options to see the default values for most options. There is no builtin or example mpv.conf with all the defaults.

Configuration files are read system-wide from /usr/local/etc/mpv.conf and per-user from ~/.config/mpv/mpv.conf, where per-user settings override system-wide settings, all of which are overridden by the command line.

Configuration file settings and the command line options use the same underlying mechanisms. Most options can be put into the configuration file by dropping the preceding '--'. See the man page for a complete list of options.

Lines starting with '#' are comments and are ignored.

See the CONFIGURATION FILES section in the man page for a detailed description of the syntax.

Profiles should be placed at the bottom of the configuration file to ensure that settings wanted as defaults are not restricted to specific profiles.

** Window
Disabling fixed aspect ratio for mpv window stops it from being launched in floating layout in qtile WM. In theory, this should make it play nicer with other tiling window managers as well.
#+begin_src conf :tangle mpv.conf
# no-keepaspect-window
#+end_src

Start in fullscreen mode by default.
#+begin_src conf :tangle mpv.conf
# fs=yes
# fs-screen=current
#+end_src

Force starting with centered window
#+begin_src conf :tangle mpv.conf
geometry=50%:50%
#+end_src

Don't allow a new window to have a size larger than 90% of the screen size
#+begin_src conf :tangle mpv.conf
autofit-larger=90%x90%
#+end_src

Keep the player window on top of all other windows.
#+begin_src conf :tangle mpv.conf
#ontop=yes
#+end_src

Do not close the window on exit.
#+begin_src conf :tangle mpv.conf
keep-open=yes
#+end_src

Do not wait with showing the video window until it has loaded. (This will resize the window once video is loaded. Also always shows a window with audio.)
#+begin_src conf :tangle mpv.conf
#force-window=immediate
#+end_src

Make mouse cursor automatically hide after given number of milliseconds.
=no= will disable cursor autohide
=always= means the cursor will stay hidden.
#+begin_src conf :tangle mpv.conf
cursor-autohide=1000
#+end_src

** Playback
#+begin_src conf :tangle mpv.conf
loop-file=no
loop-playlist=inf
#+end_src

** Video
Disable the On Screen Controller (OSC).
#+begin_src conf :tangle mpv.conf
osc=no
#+end_src

Specify high quality video rendering preset (for --vo=gpu only)
Can cause performance problems with some drivers and GPUs.
#+begin_src conf :tangle mpv.conf
profile=gpu-hq
#+end_src

Force video to lock on the display's refresh rate, and change video and audio speed to some degree to ensure synchronous playback - can cause problems with some drivers and desktop environments.
#+begin_src conf :tangle mpv.conf
#video-sync=display-resample
#+end_src

Enable hardware decoding if available. Often, this does not work with all video outputs, but should work well with default settings on most systems.
If performance or energy usage is an issue, forcing the vdpau or vaapi VOs may or may not help.
#+begin_src conf :tangle mpv.conf
#hwdec=auto
#+end_src

** Audio
Specify default audio device. You can list devices with: --audio-device=help
The option takes the device string (the stuff between the '...').
#+begin_src conf :tangle mpv.conf
#audio-device=alsa/default
#+end_src

Do not filter audio to keep pitch when changing playback speed.
#+begin_src conf :tangle mpv.conf
#audio-pitch-correction=no
#+end_src

Output 5.1 audio natively, and upmix/downmix audio with a different format.
#+begin_src conf :tangle mpv.conf
#audio-channels=5.1
#+end_src

Disable any automatic remix, _if_ the audio output accepts the audio format of the currently played file. See caveats mentioned in the manpage.
(The default is "auto-safe", see manpage.)
#+begin_src conf :tangle mpv.conf
#audio-channels=auto
#+end_src

** OSD
You can configure this on a per-command basis in input.conf using osd- prefixes, see Input Command Prefixes.

Set what is displayed on the OSD during seeks.
- =no=
- =bar= (default)
- =msg=
- =msg-bar=
#+begin_src conf :tangle mpv.conf
osd-on-seek=no
#+end_src

Set the duration of the OSD messages in ms (default: 1000).
#+begin_src conf :tangle mpv.conf
osd-duration=1000
#+end_src

Gaussian blur factor. 0 means no blur applied (default).
- 0 .. 20.0
#+begin_src conf :tangle mpv.conf
osd-blur=0
#+end_src

** Cache
Use a large seekable RAM cache even for local input.
#+begin_src conf :tangle mpv.conf
#cache=yes
#+end_src

Use extra large RAM cache (needs cache=yes to make it useful).
#+begin_src conf :tangle mpv.conf
#demuxer-max-bytes=500M
#demuxer-max-back-bytes=100M
#+end_src

Disable the behavior that the player will pause if the cache goes below a certain fill size.
#+begin_src conf :tangle mpv.conf
#cache-pause=no
#+end_src

Store cache payload on the hard disk instead of in RAM. (This may negatively impact performance unless used for slow input such as network.)
#+begin_src conf :tangle mpv.conf
#cache-dir=~/.cache/
#cache-on-disk=yes
#+end_src

** Profiles
The options declared as part of profiles override global default settings, but only take effect when the profile is active.
The following profile can be enabled on the command line with: --profile=eye-cancer
#+begin_src conf :tangle mpv.conf
#[eye-cancer]
#sharpen=5
#+end_src

** Screenshot
#+begin_src conf :tangle mpv.conf
screenshot-directory="~/Pictures/screenshots/"
screenshot-template="mpv-%F-%wH-%wM-%wS-%wT"
#+end_src

** Other
(X11 only) Control the use of NetWM protocol features.

This may or may not help with broken window managers. This provides some
functionality that was implemented by the now removed =--fstype= option. Actually,
it is not known to the developers to which degree this option was needed, so
feedback is welcome.

Specifically, yes will force use of NetWM fullscreen support, even if not
advertised by the WM. This can be useful for WMs that are broken on purpose,
like XMonad. (XMonad supposedly doesn't advertise fullscreen support, because
Flash uses it. Apparently, applications which want to use fullscreen anyway are
supposed to either ignore the NetWM support hints, or provide a workaround.
Shame on XMonad for deliberately breaking X protocols (as if X isn't bad enough
already).

By default, NetWM support is autodetected (auto).

This option might be removed in the future.
Values: =yes|no|auto=
#+begin_src conf :tangle mpv.conf
# x11-netwm=yes
#+end_src

Save playback position in between sessions
#+begin_src conf :tangle mpv.conf
save-position-on-quit=yes
#+end_src

Disable default keybindings
#+begin_src conf :tangle mpv.conf
no-input-default-bindings
#+end_src

Pretend to be a web browser. Might fix playback with some streaming sites, but also will break with shoutcast streams.
#+begin_src conf :tangle mpv.conf
#user-agent="Mozilla/5.0"
#+end_src

Display English subtitles if available.
#+begin_src conf :tangle mpv.conf
#slang=en
#+end_src

Fuzzy search subtitles
#+begin_src conf :tangle mpv.conf
sub-auto=fuzzy
#+end_src

Play Finnish audio if available, fall back to English otherwise.
#+begin_src conf :tangle mpv.conf
#alang=fi,en
#+end_src

Change subtitle encoding. For Arabic subtitles use 'cp1256'.
If the file seems to be valid UTF-8, prefer UTF-8.
(You can add '+' in front of the codepage to force it.)
#+begin_src conf :tangle mpv.conf
#sub-codepage=cp1256
#+end_src

You can also include other configuration files.
#+begin_src conf :tangle mpv.conf
#include=/path/to/the/file/you/want/to/include
#+end_src

* Scripts
** Torque Progress-bar
*** Colors
Here are some useful ASS override tags (omit square brackets)
\fn[Font Name] : sets the font to the named font.
\fs[number]    : sets the font size to the given number.
\b[1/0]        : sets the text bold or not (\b1 is bold, \b0 is regular weight).
\i[1/0]        : sets the text italic or not (same semantics as bold).
\bord[number]  : sets the outline width to the given number (in pixels).
\shad[number]  : sets the shadow size to the given number (pixels).
\c&H[BBGGRR]&  : sets the fill color for the text to the given color (hex pairs in
	             the order, blue, green, red).
\3c&H[BBGGRR]& : sets the outline color of the text to the given color.
\4c&H[BBGGRR]& : sets the shadow color of the text to the given color.
\alpha&H[AA]&  : sets the line's transparency as a hex pair. 00 is fully opaque
               and FF is fully transparent. Some UI elements are composed of
               multiple layered lines, so adding transparency may not look good.
               For further granularity, \1a&H[AA]& controls the fill opacity,
               \3a&H[AA]& controls the outline opacity, and \4a&H[AA]& controls
               the shadow opacity.
#+begin_src conf :tangle script-opts/torque-progressbar/main.conf
# Default style that is applied to all UI elements. A string of ASS override tags.
# Individual elements have their own style settings which override the tags here.
# Changing the font will likely require changing the hover-time margin settings
# and the offscreen-pos settings.
default-style=\fnSource Sans Pro\fs30\b1\bord0\shad0\c&Hb2dbeb&

# A string of ASS override tags that get applied to all three layers of the bar:
# progress, cache, and background. You probably don't want to remove \bord0 unless
# your default-style includes it.
bar-default-style=\bord0\shad0

# A string of ASS override tags that get applied only to the progress layer of the
# bar.
bar-foreground-style=\alpha&H00\c&H1d24cc& # red
# bar-foreground-style=\alpha&H00\c&H0e5dd6& # orange

# A string of ASS override tags that get applied only to the cache layer of the
# bar, particularly the part of the cache bar that is behind the current playback
# position. The default sets only the color.
bar-cache-style=\c&H646f7c&

# A string of ASS override tags that get applied only to the cache layer of the
# bar, particularly the part of the cache bar that is after the current playback
# position. The tags specified here are applied after bar-cache-style and override
# them. Leaving this blank will leave the style the same as specified by bar-
# cache-style. The split does not account for a nonzero progress-bar-width and may
# look odd when used in tandem with that setting.
bar-cache-background-style=

# A string of ASS override tags that get applied only to the background layer of
# the bar. The default sets only the color.
bar-background-style=\c&H282828&

# A string of ASS override tags that get applied only to the elapsed time display.
elapsed-style=

# A string of ASS override tags that get applied only to the remaining time
# display.
remaining-style=

# A string of ASS override tags that get applied only to the hover time display.
# Unfortunately, due to the way the hover time display is animated, alpha values
# set here will be overridden. This is subject to change in future versions.
hover-time-style=\fs26

# A string of ASS override tags that get applied only to the video title display.
title-style=

# A string of ASS override tags that get applied only to the system time display.
system-time-style=

# A string of ASS override tags that get applied only to the foreground of the
# pause indicator.
pause-indicator-foreground-style=\c&Hb2dbeb&

# A string of ASS override tags that get applied only to the background of the
# pause indicator.
pause-indicator-background-style=\c&H282828&

# A string of ASS override tags that get applied only to chapter markers that have
# not yet been passed.
chapter-marker-before-style=\c&H000000&

# A string of ASS override tags that get applied only to chapter markers that have
# already been passed.
chapter-marker-after-style=\c&H000000&

#+end_src

*** UI
#+begin_src conf :tangle script-opts/torque-progressbar/main.conf
# Controls whether or not the progress bar is drawn at all. If this is disabled,
# it also (naturally) disables the click-to-seek functionality.
enable-bar=yes

# Causes the bar to not be drawn unless the mouse is hovering over it or a
# request-display call is active. This is somewhat redundant with setting bar-
# height-inactive=0, except that it can allow for very rudimentary context-
# sensitive behavior because it can be toggled at runtime. For example, by using
# the binding `f cycle pause; script-binding progressbar/toggle-inactive-bar`, it
# is possible to have the bar be persistently present only in windowed or
# fullscreen contexts, depending on the default setting.
bar-hide-inactive=no

# If greater than zero, changes the progress bar style to be a small segment
# rather than a continuous bar and sets its width.
progress-bar-width=0

# Affects precision of seeks due to clicks on the progress bar. Should be 'exact' or
# 'keyframes'. Exact is slightly slower, but won't jump around between two
# different times when clicking in the same place.
#
# Actually, this gets passed directly into the `seek` command, so the value can be
# any of the arguments supported by mpv, though the ones above are the only ones
# that really make sense.
seek-precision=exact

# Causes the progress bar background layer to automatically size itself to the
# tallest of the cache or progress bars. Useful for improving contrast but can
# make the bar take up more screen space. Has no effect if the cache bar height is
# less than the bar height.
bar-background-adaptive=yes

# Placement of the cache bar. Valid values are 'overlay' and 'underlay'.
#
# 'overlay' causes the cache bar to be drawn on top of the foreground layer of the
# bar, allowing the display of seek ranges that have already been encountered.
#
# 'underlay' draws the cache bar between the foreground and background layers. Any
# demuxer cache ranges that are prior to the current playback point will not be
# shown. This matches the previous behavior.
bar-cache-position=underlay

# Sets the height of the rectangular area at the top of the screen that shows the
# file name and system time when the mouse is hovered over it.
top-hover-zone-height=40

# Acts as a multiplier to increase the size of every UI element. Useful for high-
# DPI displays that cause the UI to be rendered too small (happens at least on
# macOS).
display-scale-factor=1

# Sets whether or not the pause indicator is displayed. The pause indicator is a
# momentary icon that flashes in the middle of the screen, similar to youtube.
pause-indicator=yes
#+end_src

*** Bar
Inactive
#+begin_src conf :tangle script-opts/torque-progressbar/main.conf
# Sets the height of the bar display when the mouse is not in the active zone and
# there is no request-display active. A value of 0 or less will cause bar-hide-
# inactive to be set to true and the bar height to be set to 1. This should result
# in the desired behavior while avoiding annoying debug logging in mpv (libass
# does not like zero-height objects).
bar-height-inactive=3

# Sets the height of the cache bar display when the mouse is not in the active
# zone and there is no request-display active. Useful in combination with bar-
# cache-position to control whether or not the cache bar is occluded by (or
# occludes) the progress bar.
bar-cache-height-inactive=3

#+end_src

Active
#+begin_src conf :tangle script-opts/torque-progressbar/main.conf
# Sets the height of the rectangular area at the bottom of the screen that expands
# the progress bar and shows playback time information when the mouse is hovered
# over it.
hover-zone-height=40

# Sets the height of the bar display when the mouse is in the active zone or
# request-display is active. There is no logic attached to this, so 0 or negative
# values may have unexpected results.
bar-height-active=20

# Sets the height of the cache bar display when the mouse is in the active zone or
# request-display is active. Useful in combination with bar-cache- position to
# control whether or not the cache bar is occluded by (or occludes) the progress
# bar.
bar-cache-height-active=20
#+end_src

*** Title
#+begin_src conf :tangle script-opts/torque-progressbar/main.conf
# Sets whether or not the video title is displayed at all.
enable-title=yes

# Controls how far from the left edge of the window the video title display is
# positioned.
title-left-margin=4

# Controls how far from the top edge of the window the video title display is
# positioned.
title-top-margin=0

# Controls whether or not the script logs the video title and playlist position
# to the console every time a new video starts.
title-print-to-cli=yes

# Controls how far off the left side of the window the video title display tries
# to move when it is inactive. If you use a non-default font, this value may need
# to be tweaked. If this value is not far enough off-screen, the elapsed display
# will disappear without animating all the way off-screen. Positive values will
# cause the display to animate the wrong direction.
title-offscreen-pos=-40
#+end_src

*** Clock
#+begin_src conf :tangle script-opts/torque-progressbar/main.conf
# Sets whether or not the system time is displayed at all.
enable-system-time=yes

# Sets the format used for the system time display. This must be a strftime-
# compatible format string.
system-time-format=%I:%M %p

# Controls how far from the right edge of the window the system time display is
# positioned.
system-time-right-margin=4

# Controls how far from the top edge of the window the system time display is
# positioned.
system-time-top-margin=0

# Controls how far off the left side of the window the system time display tries
# to move when it is inactive. If you use a non-default font, this value may need
# to be tweaked. If this value is not far enough off-screen, the elapsed display
# will disappear without animating all the way off-screen. Positive values will
# cause the display to animate the wrong direction.
system-time-offscreen-pos=-100
#+end_src

*** Seek Time
Elapsed
#+begin_src conf :tangle script-opts/torque-progressbar/main.conf
# Sets whether or not the elapsed time is displayed at all.
enable-elapsed-time=yes

# Controls how far from the left edge of the window the elapsed time display is
# positioned.
elapsed-left-margin=4

# Controls how far above the expanded progress bar the elapsed time display is
# positioned.
elapsed-bottom-margin=0

# Controls how far off the left side of the window the elapsed time display tries
# to move when it is inactive. If you use a non-default font, this value may need
# to be tweaked. If this value is not far enough off-screen, the elapsed display
# will disappear without animating all the way off-screen. Positive values will
# cause the display to animate the wrong direction.
elapsed-offscreen-pos=-100
#+end_src

Remaining
#+begin_src conf :tangle script-opts/torque-progressbar/main.conf
# Sets whether or not the remaining time is displayed at all.
enable-remaining-time=yes

# Controls how far from the right edge of the window the remaining time display is
# positioned.
remaining-right-margin=4

# Controls how far above the expanded progress bar the remaining time display is
# positioned.
remaining-bottom-margin=0

# Controls how far off the left side of the window the remaining time display
# tries to move when it is inactive. If you use a non-default font, this value may
# need to be tweaked. If this value is not far enough off-screen, the elapsed
# display will disappear without animating all the way off-screen. Positive values
# will cause the display to animate the wrong direction.
remaining-offscreen-pos=-100
#+end_src

Hover
#+begin_src conf :tangle script-opts/torque-progressbar/main.conf
# Sets whether or not the calculated time corresponding to the mouse position
# is displayed when the mouse hovers over the progress bar.
enable-hover-time=yes

# Controls how close to the left edge of the window the hover time display can
# get. If this value is too small, it will end up overlapping the elapsed time
# display.
hover-time-left-margin=120

# Controls how close to the right edge of the window the hover time display can
# get. If this value is too small, it will end up overlapping the remaining time
# display.
hover-time-right-margin=130

# Controls how far above the expanded progress bar the remaining time display is
# positioned.
hover-time-bottom-margin=0

# Controls how far off the bottom of the window the mouse hover time display tries
# to move when it is inactive. If you use a non-default font, this value may need
# to be tweaked. If this value is not far enough off-screen, the elapsed
# display will disappear without animating all the way off-screen. Positive values
# will cause the display to animate the wrong direction.
hover-time-offscreen-pos=-50
#+end_src

*** Chapter Markers
#+begin_src conf :tangle script-opts/torque-progressbar/main.conf
# Sets whether or not the progress bar is decorated with chapter markers. Due to
# the way the chapter markers are currently implemented, videos with a large
# number of chapters may slow down the script somewhat, but I have yet to run
# into this being a problem.
enable-chapter-markers=yes

# Controls the width of each chapter marker when the progress bar is inactive.
chapter-marker-width=2

# Controls the width of each chapter marker when the progress bar is active.
chapter-marker-width-active=4

# Modifies the height of the chapter markers when the progress bar is active. Acts
# as a multiplier on the height of the active progress bar. A value greater than 1
# will cause the markers to be taller than the expanded progress bar, whereas a
# value less than 1 will cause them to be shorter.
chapter-marker-active-height-fraction=1
#+end_src

*** Timing
#+begin_src conf :tangle script-opts/torque-progressbar/main.conf
# Sets the amount of time in seconds that the UI stays on the screen after it
# receives a request-display signal. A value of 0 will keep the display on screen
# only as long as the key bound to it is held down.
request-display-duration=2

# Controls how often the display is redrawn, in seconds. This does not seem to
# significantly affect the smoothness of animations, and it is subject to the
# accuracy limits imposed by the scheduler mpv uses. Probably not worth changing
# unless you have major performance problems.
redraw-period=0.03

# Controls how long the UI animations take. A value of 0 disables all animations
# (which breaks the pause indicator).
animation-duration=0.25

#+end_src

** yt-dlp
#+begin_src conf :tangle script-opts/yt-dlp/main.conf
ytdl_hook-ytdl_path=/usr/bin/yt-dlp
#+end_src

* Keybindings
** Info
List of commands and further details: DOCS/man/input.rst
List of special keys: --input-keylist
Keybindings testing mode: mpv --input-test --force-window --idle

Use 'ignore' to unbind a key fully (e.g. 'ctrl+a ignore').

Strings need to be quoted and escaped:
- KEY show-text "This is a single backslash: \\ and a quote: \" !"

You can use modifier-key combinations like Shift+Left or Ctrl+Alt+x with the modifiers Shift, Ctrl, Alt and Meta (may not work on the terminal).

The default keybindings are hardcoded into the mpv binary. You can disable them completely with: --no-input-default-bindings

Developer note:
On compilation, this file is baked into the mpv binary, and all lines are uncommented (unless '#' is followed by a space) - thus this file defines the default key bindings.

** Initialization
If this is enabled, treat all the following bindings as default.
#+begin_src conf :tangle input.conf
# default-bindings start
#+end_src

** Window
#+begin_src conf :tangle input.conf
q quit
Q quit-watch-later
q {encode} quit 4
ESC {encode} quit 4
ctrl+c quit 4

_ cycle video
T cycle ontop                          # toggle video window ontop of other windows

ESC set fullscreen no
f cycle fullscreen                     # toggle fullscreen
#+end_src

#+begin_src conf :tangle input.conf
#Alt+0 set window-scale 0.5
#Alt+1 set window-scale 1.0
#Alt+2 set window-scale 2.0
#+end_src

** Playback
#+begin_src conf :tangle input.conf
k     cycle pause
SPACE cycle pause
#+end_src

Scale playback speed
#+begin_src conf :tangle input.conf
# [ multiply speed 1/1.1
# ] multiply speed 1.1
# { multiply speed 0.5
# } multiply speed 2.0
#+end_src

#+begin_src conf :tangle input.conf
[ multiply speed 1/1.1
] multiply speed 1.1
{ add speed -0.25
} add speed 0.25
#+end_src

Reset speed to normal
#+begin_src conf :tangle input.conf
BS set speed 1.0
#+end_src

A-B Loop
#+begin_src conf :tangle input.conf
\ ab-loop                              # Set/clear A-B loop points
#L cycle-values loop-file "inf" "no"    # toggle infinite looping
#+end_src

** Navigation
Seek units are in seconds, but note that these are limited by keyframes
#+begin_src conf :tangle input.conf
j           seek -5
l           seek  5
J           seek -15
L           seek  15

LEFT        seek -10
RIGHT       seek  10

Shift+LEFT  seek -30
Shift+RIGHT seek  30
Shift+DOWN  seek -60
Shift+UP    seek  60
#+end_src

Frame-by-frame navigation
#+begin_src conf :tangle input.conf
. frame-step                           # advance one frame and pause
, frame-back-step                      # go back by one frame and pause
#+end_src

#+begin_src conf :tangle input.conf
HOME seek 0 absolute-percent
END  set pause yes ; seek 100 absolute-percent

0 seek 0 absolute-percent
1 seek 10 absolute-percent
2 seek 20 absolute-percent
3 seek 30 absolute-percent
4 seek 40 absolute-percent
5 seek 50 absolute-percent
6 seek 60 absolute-percent
7 seek 70 absolute-percent
8 seek 80 absolute-percent
9 seek 90 absolute-percent
$ set pause yes ; seek 100 absolute-percent
#+end_src

#+begin_src conf :tangle input.conf
#Shift+PGUP seek 600
#Shift+PGDWN seek -600
#Shift+BS revert-seek                   # undo previous (or marked) seek
#Shift+Ctrl+BS revert-seek mark         # mark position for revert-seek
#+end_src

** Playlists
#+begin_src conf :tangle input.conf
p show_text ${playlist} # show playlist
# ENTER playlist-next   # skip to next file
Shift+n playlist-next   # skip to next file
Shift+p playlist-prev   # skip to previous file
>       playlist-next   # skip to next file
<       playlist-prev   # skip to previous file
#+end_src

** Audio
#+begin_src conf :tangle input.conf
UP    add volume 1
DOWN  add volume -1
m     cycle mute

#ctrl++ add audio-delay 0.100           # this changes audio/video sync
#ctrl+- add audio-delay -0.100

#F9 show_text ${track-list}             # show list of audio/sub streams

#SHARP cycle audio                      # switch audio streams
#+end_src

** OSD
Legacy
#+begin_src conf :tangle input.conf
# o show-progress
# O no-osd cycle-values osd-level 3 1    # cycle through OSD mode
# Ctrl+o script-binding osc/visibility      # cycle OSC display
#+end_src

Torque Progressbar
#+begin_src conf :tangle input.conf
o script-binding progressbar/request-display
Ctrl+o script-binding progressbar/toggle-inactive-bar
. script-binding progressbar/step-forward
, script-binding progressbar/step-backward
#+end_src

Info
#+begin_src conf :tangle input.conf
i     script-binding stats/display-stats
I     script-binding stats/display-stats-toggle
`     script-binding console/enable
:     script-binding console/enable
Alt+x script-binding console/enable
#+end_src

** Subtitles
Skip to previous/next subtitle (subject to some restrictions; see manpage)
#+begin_src conf :tangle input.conf
Alt+LEFT   no-osd sub-seek -1
Alt+RIGHT  no-osd sub-seek  1
#+end_src

#+begin_src conf :tangle input.conf
v cycle sub-visibility
c cycle sub-visibility

# stretch SSA/ASS subtitles with anamorphic videos to match historical
V cycle sub-ass-vsfilter-aspect-compat
C cycle sub-ass-vsfilter-aspect-compat

# switch between applying no style overrides to SSA/ASS subtitles, and
# overriding them almost completely with the normal subtitle style
#u cycle-values sub-ass-override "force" "no"
s cycle sub                            # cycle through subtitles
S cycle sub down                       # ...backwards

#Shift+g add sub-scale +0.1            # increase subtitle font size
#Shift+f add sub-scale -0.1            # decrease subtitle font size

#z add sub-delay -0.1                  # subtract 100 ms delay from subs
#Z add sub-delay +0.1                  # add
#x add sub-delay +0.1                  # same as previous binding (discouraged)

#r add sub-pos -1                      # move subtitles up
#R add sub-pos +1                      #                down
#t add sub-pos +1                      # same as previous binding (discouraged)

# Adjust timing to previous/next subtitle
#Ctrl+Shift+LEFT sub-step -1
#Ctrl+Shift+RIGHT sub-step 1
#+end_src

** Screenshot
Take screenshot without subtitles
#+begin_src conf :tangle input.conf
Ctrl+PRINT screenshot video
F12        screenshot video
Alt+s      screenshot video
Alt+S      screenshot each-frame            # automatically screenshot every frame
#+end_src

** Image Adjustment
#+begin_src conf :tangle input.conf
Alt+1 add contrast -1
Alt+2 add contrast 1
Alt+3 add brightness -1
Alt+4 add brightness 1
Alt+5 add gamma -1
Alt+6 add gamma 1
Alt+7 add saturation -1
Alt+8 add saturation 1

# toggle deinterlacer (automatically inserts or removes required filter)
Alt+d cycle deinterlace

#w add panscan -0.1                     # zoom out with -panscan 0 -fs
#W add panscan +0.1                     #      in
#e add panscan +0.1                     # same as previous binding (discouraged)

# Move video rectangle
Ctrl+left  add video-pan-x  0.1
Ctrl+right add video-pan-x -0.1
Ctrl+up    add video-pan-y  0.1
Ctrl+down  add video-pan-y -0.1
Alt+h      add video-pan-x  0.1
Alt+l      add video-pan-x -0.1
Alt+k      add video-pan-y  0.1
Alt+j      add video-pan-y -0.1

# Zoom/unzoom video
Ctrl+0     set video-zoom 0
Ctrl+-     add video-zoom -0.25
Ctrl+=     add video-zoom 0.25

# Reset video zoom/pan settings
Ctrl+BS set video-zoom 0 ; set video-pan-x 0 ; set video-pan-y 0

# cycle video aspect ratios; "-1" is the container aspect
Alt+a cycle-values video-aspect-override "16:9" "4:3" "2.35:1" "-1"
#+end_src

** Chapters
Jump between chapters
#+begin_src conf :tangle input.conf
PGDWN  add chapter -1
PGUP   add chapter 1
Ctrl+j add chapter -1
Ctrl+l add chapter 1
#+end_src

** Media Keys
#+begin_src conf :tangle input.conf
#POWER      quit
PLAY        cycle pause
PAUSE       cycle pause
PLAYPAUSE   cycle pause
PLAYONLY    set pause no
PAUSEONLY   set pause yes
STOP        set pause no
FORWARD     seek 60
REWIND      seek -60
NEXT        playlist-next
PREV        playlist-prev
VOLUME_UP   add volume 2
VOLUME_DOWN add volume -2
MUTE        cycle mute
CLOSE_WIN   quit
CLOSE_WIN   {encode} quit 4
#+end_src

** Mouse Bindings
#+begin_src conf :tangle input.conf
MBTN_RIGHT_DBL quit
MBTN_LEFT      cycle pause ; script-binding progressbar/left-click
MBTN_LEFT_DBL  cycle fullscreen    # toggle fullscreen on/off
MBTN_RIGHT     script-binding progressbar/left-click
MBTN_BACK      playlist-prev
MBTN_FORWARD   playlist-next
#+end_src

Mouse wheels, touch-pad or other input devices that have axes if the input devices supports precise scrolling it will also scale the numeric value accordingly
#+begin_src conf :tangle input.conf
WHEEL_UP      add volume 1
WHEEL_DOWN    add volume -1
WHEEL_LEFT    seek -1
WHEEL_RIGHT   seek 1
#+end_src

** Misc
#+begin_src conf :tangle input.conf
E cycle edition                        # next edition
#ctrl+h cycle-values hwdec "auto" "no"  # cycle hardware decoding
#+end_src
