#+TITLE: MPV
#+AUTHOR: Artem Smaznov
#+STARTUP: overview

* Config
** Warning
The commented example options usually do _not_ set the default values. Call mpv with --list-options to see the default values for most options. There is no builtin or example mpv.conf with all the defaults.

Configuration files are read system-wide from /usr/local/etc/mpv.conf and per-user from ~/.config/mpv/mpv.conf, where per-user settings override system-wide settings, all of which are overridden by the command line.

Configuration file settings and the command line options use the same underlying mechanisms. Most options can be put into the configuration file by dropping the preceding '--'. See the man page for a complete list of options.

Lines starting with '#' are comments and are ignored.

See the CONFIGURATION FILES section in the man page for a detailed description of the syntax.

Profiles should be placed at the bottom of the configuration file to ensure that settings wanted as defaults are not restricted to specific profiles.

** Window
Disabling fixed aspect ratio for mpv window stops it from being launched in floating layout in qtile WM. In theory, this should make it play nicer with other tiling window managers as well.
#+begin_src conf :tangle mpv.conf
no-keepaspect-window
#+end_src

Start in fullscreen mode by default.
#+begin_src conf :tangle mpv.conf
# fs=yes
# fs-screen=current
#+end_src

Force starting with centered window
#+begin_src conf :tangle mpv.conf
# geometry=50%:50%
#+end_src

Don't allow a new window to have a size larger than 90% of the screen size
#+begin_src conf :tangle mpv.conf
# autofit-larger=90%x90%
#+end_src

Keep the player window on top of all other windows.
#+begin_src conf :tangle mpv.conf
#ontop=yes
#+end_src

Do not close the window on exit.
#+begin_src conf :tangle mpv.conf
keep-open=yes
#+end_src

Do not wait with showing the video window until it has loaded. (This will resize the window once video is loaded. Also always shows a window with audio.)
#+begin_src conf :tangle mpv.conf
#force-window=immediate
#+end_src

Make mouse cursor automatically hide after given number of milliseconds.
=no= will disable cursor autohide
=always= means the cursor will stay hidden.
#+begin_src conf :tangle mpv.conf
cursor-autohide=1000
#+end_src

** Playback
#+begin_src conf :tangle mpv.conf
loop-file=inf
loop-playlist=no
#+end_src

** Video
Disable the On Screen Controller (OSC).
#+begin_src conf :tangle mpv.conf
#osc=no
#+end_src

Specify high quality video rendering preset (for --vo=gpu only)
Can cause performance problems with some drivers and GPUs.
#+begin_src conf :tangle mpv.conf
profile=gpu-hq
#+end_src

Force video to lock on the display's refresh rate, and change video and audio speed to some degree to ensure synchronous playback - can cause problems with some drivers and desktop environments.
#+begin_src conf :tangle mpv.conf
#video-sync=display-resample
#+end_src

Enable hardware decoding if available. Often, this does not work with all video outputs, but should work well with default settings on most systems.
If performance or energy usage is an issue, forcing the vdpau or vaapi VOs may or may not help.
#+begin_src conf :tangle mpv.conf
#hwdec=auto
#+end_src

** Audio
Specify default audio device. You can list devices with: --audio-device=help
The option takes the device string (the stuff between the '...').
#+begin_src conf :tangle mpv.conf
#audio-device=alsa/default
#+end_src

Do not filter audio to keep pitch when changing playback speed.
#+begin_src conf :tangle mpv.conf
#audio-pitch-correction=no
#+end_src

Output 5.1 audio natively, and upmix/downmix audio with a different format.
#+begin_src conf :tangle mpv.conf
#audio-channels=5.1
#+end_src

Disable any automatic remix, _if_ the audio output accepts the audio format of the currently played file. See caveats mentioned in the manpage.
(The default is "auto-safe", see manpage.)
#+begin_src conf :tangle mpv.conf
#audio-channels=auto
#+end_src

** OSD
You can configure this on a per-command basis in input.conf using osd- prefixes, see Input Command Prefixes.

Set what is displayed on the OSD during seeks.
- =no=
- =bar= (default)
- =msg=
- =msg-bar=
#+begin_src conf :tangle mpv.conf
osd-on-seek=msg-bar
#+end_src

Set the duration of the OSD messages in ms (default: 1000).
#+begin_src conf :tangle mpv.conf
osd-durtaion=1000
#+end_src

Gaussian blur factor. 0 means no blur applied (default).
- 0 .. 20.0
#+begin_src conf :tangle mpv.conf
osd-blur=0
#+end_src

** Cache
Use a large seekable RAM cache even for local input.
#+begin_src conf :tangle mpv.conf
#cache=yes
#+end_src

Use extra large RAM cache (needs cache=yes to make it useful).
#+begin_src conf :tangle mpv.conf
#demuxer-max-bytes=500M
#demuxer-max-back-bytes=100M
#+end_src

Disable the behavior that the player will pause if the cache goes below a certain fill size.
#+begin_src conf :tangle mpv.conf
#cache-pause=no
#+end_src

Store cache payload on the hard disk instead of in RAM. (This may negatively impact performance unless used for slow input such as network.)
#+begin_src conf :tangle mpv.conf
#cache-dir=~/.cache/
#cache-on-disk=yes
#+end_src

** Profiles
The options declared as part of profiles override global default settings, but only take effect when the profile is active.
The following profile can be enabled on the command line with: --profile=eye-cancer
#+begin_src conf :tangle mpv.conf
#[eye-cancer]
#sharpen=5
#+end_src

** Screenshot
#+begin_src conf :tangle mpv.conf
screenshot-directory="~/Pictures/Screenshots/"
screenshot-template="mpv-%F-%wH-%wM-%wS-%wT"
#+end_src

** Other
Save playback position in between sessions
#+begin_src conf :tangle mpv.conf
save-position-on-quit=yes
#+end_src

Disable default keybindings
#+begin_src conf :tangle mpv.conf
no-input-default-bindings
#+end_src

Pretend to be a web browser. Might fix playback with some streaming sites, but also will break with shoutcast streams.
#+begin_src conf :tangle mpv.conf
#user-agent="Mozilla/5.0"
#+end_src

Display English subtitles if available.
#+begin_src conf :tangle mpv.conf
#slang=en
#+end_src

Fuzzy search subtitles
#+begin_src conf :tangle mpv.conf
sub-auto=fuzzy
#+end_src

Play Finnish audio if available, fall back to English otherwise.
#+begin_src conf :tangle mpv.conf
#alang=fi,en
#+end_src

Change subtitle encoding. For Arabic subtitles use 'cp1256'.
If the file seems to be valid UTF-8, prefer UTF-8.
(You can add '+' in front of the codepage to force it.)
#+begin_src conf :tangle mpv.conf
#sub-codepage=cp1256
#+end_src

You can also include other configuration files.
#+begin_src conf :tangle mpv.conf
#include=/path/to/the/file/you/want/to/include
#+end_src

* Keybindings
** Info
List of commands and further details: DOCS/man/input.rst
List of special keys: --input-keylist
Keybindings testing mode: mpv --input-test --force-window --idle

Use 'ignore' to unbind a key fully (e.g. 'ctrl+a ignore').

Strings need to be quoted and escaped:
- KEY show-text "This is a single backslash: \\ and a quote: \" !"

You can use modifier-key combinations like Shift+Left or Ctrl+Alt+x with the modifiers Shift, Ctrl, Alt and Meta (may not work on the terminal).

The default keybindings are hardcoded into the mpv binary. You can disable them completely with: --no-input-default-bindings

Developer note:
On compilation, this file is baked into the mpv binary, and all lines are uncommented (unless '#' is followed by a space) - thus this file defines the default key bindings.

** Initialization
If this is enabled, treat all the following bindings as default.
#+begin_src conf :tangle input.conf
# default-bindings start
#+end_src

** Window
#+begin_src conf :tangle input.conf
q quit
Q quit-watch-later
q {encode} quit 4
ESC {encode} quit 4
ctrl+c quit 4

_ cycle video
T cycle ontop                          # toggle video window ontop of other windows

ESC set fullscreen no
f cycle fullscreen                     # toggle fullscreen
#+end_src

#+begin_src conf :tangle input.conf
#Alt+0 set window-scale 0.5
#Alt+1 set window-scale 1.0
#Alt+2 set window-scale 2.0
#+end_src

** Navigation & Volume
Seek units are in seconds, but note that these are limited by keyframes
#+begin_src conf :tangle input.conf
h seek -5
l seek 5
k add volume 2
j add volume -2

H seek -30
L seek 30
K seek 60
J seek -60

LEFT  seek -5
RIGHT seek  5
UP    add volume 2
DOWN  add volume -2

Shift+LEFT  seek -30
Shift+RIGHT seek 30
Shift+UP    seek 60
Shift+DOWN  seek -60
#+end_src

Frame-by-frame navigation
#+begin_src conf :tangle input.conf
. frame-step                           # advance one frame and pause
, frame-back-step                      # go back by one frame and pause
#+end_src

#+begin_src conf :tangle input.conf
HOME seek 0 absolute-percent
END set pause yes ; seek 100 absolute-percent

0 seek 0 absolute-percent
1 seek 10 absolute-percent
2 seek 20 absolute-percent
3 seek 30 absolute-percent
4 seek 40 absolute-percent
5 seek 50 absolute-percent
6 seek 60 absolute-percent
7 seek 70 absolute-percent
8 seek 80 absolute-percent
9 seek 90 absolute-percent
#+end_src

#+begin_src conf :tangle input.conf
#Shift+PGUP seek 600
#Shift+PGDWN seek -600
#Shift+BS revert-seek                   # undo previous (or marked) seek
#Shift+Ctrl+BS revert-seek mark         # mark position for revert-seek
#+end_src

** Playback
#+begin_src conf :tangle input.conf
SPACE cycle pause
#+end_src

Scale playback speed
#+begin_src conf :tangle input.conf
[ multiply speed 1/1.1
] multiply speed 1.1
{ multiply speed 0.5
} multiply speed 2.0
#+end_src

Reset speed to normal
#+begin_src conf :tangle input.conf
BS set speed 1.0
#+end_src

A-B Loop
#+begin_src conf :tangle input.conf
ctrl+l ab-loop                              # Set/clear A-B loop points
#L cycle-values loop-file "inf" "no"    # toggle infinite looping
#+end_src

** Playlists
#+begin_src conf :tangle input.conf
p show_text ${playlist} # show playlist
# ENTER playlist-next     # skip to next file
Shift+n playlist-next   # skip to next file
Shift+p playlist-prev   # skip to previous file
> playlist-next   # skip to next file
< playlist-prev   # skip to previous file
#+end_src

** Audio
#+begin_src conf :tangle input.conf
m cycle mute

#ctrl++ add audio-delay 0.100           # this changes audio/video sync
#ctrl+- add audio-delay -0.100

#F9 show_text ${track-list}             # show list of audio/sub streams

#SHARP cycle audio                      # switch audio streams
#+end_src

** OSD
#+begin_src conf :tangle input.conf
o show-progress
O no-osd cycle-values osd-level 3 1    # cycle through OSD mode
Ctrl+o script-binding osc/visibility      # cycle OSC display
#+end_src

Info
#+begin_src conf :tangle input.conf
i script-binding stats/display-stats
I script-binding stats/display-stats-toggle
` script-binding console/enable
Alt+x script-binding console/enable
#+end_src

** Subtitles
Skip to previous/next subtitle (subject to some restrictions; see manpage)
#+begin_src conf :tangle input.conf
Ctrl+LEFT   no-osd sub-seek -1
Ctrl+RIGHT  no-osd sub-seek  1
#+end_src

#+begin_src conf :tangle input.conf
v cycle sub-visibility

# stretch SSA/ASS subtitles with anamorphic videos to match historical
V cycle sub-ass-vsfilter-aspect-compat

# switch between applying no style overrides to SSA/ASS subtitles, and
# overriding them almost completely with the normal subtitle style
#u cycle-values sub-ass-override "force" "no"
c cycle sub                            # cycle through subtitles
C cycle sub down                       # ...backwards

#Shift+g add sub-scale +0.1                  # increase subtitle font size
#Shift+f add sub-scale -0.1                  # decrease subtitle font size

#z add sub-delay -0.1                   # subtract 100 ms delay from subs
#Z add sub-delay +0.1                   # add
#x add sub-delay +0.1                   # same as previous binding (discouraged)

#r add sub-pos -1                       # move subtitles up
#R add sub-pos +1                       #                down
#t add sub-pos +1                       # same as previous binding (discouraged)

# Adjust timing to previous/next subtitle
#Ctrl+Shift+LEFT sub-step -1
#Ctrl+Shift+RIGHT sub-step 1
#+end_src

** Screenshot
Take screenshot without subtitles
#+begin_src conf :tangle input.conf
Ctrl+PRINT screenshot video
F12 screenshot video
Alt+s screenshot video
Alt+S screenshot each-frame            # automatically screenshot every frame
#+end_src

** Image Adjustment
#+begin_src conf :tangle input.conf
Alt+1 add contrast -1
Alt+2 add contrast 1
Alt+3 add brightness -1
Alt+4 add brightness 1
Alt+5 add gamma -1
Alt+6 add gamma 1
Alt+7 add saturation -1
Alt+8 add saturation 1

# toggle deinterlacer (automatically inserts or removes required filter)
Alt+d cycle deinterlace

#w add panscan -0.1                     # zoom out with -panscan 0 -fs
#W add panscan +0.1                     #      in
#e add panscan +0.1                     # same as previous binding (discouraged)

# Move video rectangle
Alt+left  add video-pan-x  0.1
Alt+right add video-pan-x -0.1
Alt+up    add video-pan-y  0.1
Alt+down  add video-pan-y -0.1

# Zoom/unzoom video
Ctrl+0           set video-zoom 0
Ctrl+-           add video-zoom -0.25
Ctrl+=           add video-zoom 0.25

# Reset video zoom/pan settings
Ctrl+BS set video-zoom 0 ; set video-pan-x 0 ; set video-pan-y 0

# cycle video aspect ratios; "-1" is the container aspect
Alt+a cycle-values video-aspect-override "16:9" "4:3" "2.35:1" "-1"
#+end_src

** Chapters
#+begin_src conf :tangle input.conf
PGDWN add chapter -1                   # skip to previous chapter
PGUP add chapter 1                     # skip to next chapter

Alt+h add chapter -1                   # skip to previous chapter
Alt+l add chapter 1                     # skip to next chapter
#+end_src

** Media Keys
#+begin_src conf :tangle input.conf
#POWER quit
PLAY cycle pause
PAUSE cycle pause
PLAYPAUSE cycle pause
PLAYONLY set pause no
PAUSEONLY set pause yes
STOP set pause no
FORWARD seek 60
REWIND seek -60
NEXT playlist-next
PREV playlist-prev
VOLUME_UP add volume 2
VOLUME_DOWN add volume -2
MUTE cycle mute
CLOSE_WIN quit
CLOSE_WIN {encode} quit 4
#+end_src

** Mouse Bindings
#+begin_src conf :tangle input.conf
MBTN_LEFT     cycle pause
MBTN_LEFT_DBL cycle fullscreen    # toggle fullscreen on/off
MBTN_RIGHT    ignore              # don't do anything
MBTN_BACK     playlist-prev
MBTN_FORWARD  playlist-next
#+end_src

Mouse wheels, touch-pad or other input devices that have axes if the input devices supports precise scrolling it will also scale the numeric value accordingly
#+begin_src conf :tangle input.conf
WHEEL_UP      add volume 2
WHEEL_DOWN    add volume -2
WHEEL_LEFT    seek -5
WHEEL_RIGHT   seek 5
#+end_src

** Misc
#+begin_src conf :tangle input.conf
E cycle edition                        # next edition
#ctrl+h cycle-values hwdec "auto" "no"  # cycle hardware decoding
#+end_src
