# Base16 Gruvbox dark, medium - alacritty color config
# Dawid Kurek (dawikur@gmail.com), morhetz (https://github.com/morhetz/gruvbox)

[colors]
draw_bold_text_with_bright_colors = false

[colors.primary]
background = "0x282828"
foreground = "0xd5c4a1"

[colors.cursor]
cursor = "0xd5c4a1"
text = "0x282828"

[colors.normal]
black = "0x282828"
blue = "0x83a598"
cyan = "0x8ec07c"
green = "0xb8bb26"
magenta = "0xd3869b"
red = "0xfb4934"
white = "0xd5c4a1"
yellow = "0xfabd2f"

[colors.bright]
black = "0x665c54"
blue = "0xbdae93"
cyan = "0xd65d0e"
green = "0x3c3836"
magenta = "0xebdbb2"
red = "0xfe8019"
white = "0xfbf1c7"
yellow = "0x504945"
