#+TITLE: BTop
#+AUTHOR: Artem Smaznov
#+DESCRIPTION: Interractive process viewer
#+STARTUP: overview

Name of a btop++/bpytop/bashtop formatted ".theme" file, "Default" and "TTY" for builtin themes.
Themes should be placed in "../share/btop/themes" relative to binary or "$HOME/.config/btop/themes"
#+begin_src conf :tangle btop.conf
color_theme = "/usr/share/btop/themes/gruvbox_material_dark.theme"
#+end_src

If the theme set background should be shown, set to False if you want terminal background transparency.
#+begin_src conf :tangle btop.conf
theme_background = False
#+end_src

Sets if 24-bit truecolor should be used, will convert 24-bit colors to 256 color (6x6x6 color cube) if false.
#+begin_src conf :tangle btop.conf
truecolor = True
#+end_src

Set to true to force tty mode regardless if a real tty has been detected or not.
Will force 16-color mode and TTY theme, set all graph symbols to "tty" and swap out other non tty friendly symbols.
#+begin_src conf :tangle btop.conf
force_tty = False
#+end_src

Define presets for the layout of the boxes. Preset 0 is always all boxes shown with default settings. Max 9 presets.
Format: "box_name:P:G,box_name:P:G" P=(0 or 1) for alternate positions, G=graph symbol to use for box.
Use withespace " " as separator between different presets.
Example: "cpu:0:default,mem:0:tty,proc:1:default cpu:0:braille,proc:0:tty"
#+begin_src conf :tangle btop.conf
presets = "cpu:1:default,proc:0:default cpu:0:default,mem:0:default,net:0:default cpu:0:block,net:0:tty"
#+end_src

Set to True to enable "h,j,k,l" keys for directional control in lists.
Conflicting keys for h:"help" and k:"kill" is accessible while holding shift.
#+begin_src conf :tangle btop.conf
vim_keys = True
#+end_src

Rounded corners on boxes, is ignored if TTY mode is ON.
#+begin_src conf :tangle btop.conf
rounded_corners = True
#+end_src

Default symbols to use for graph creation, "braille", "block" or "tty".
"braille" offers the highest resolution but might not be included in all fonts.
"block" has half the resolution of braille but uses more common characters.
"tty" uses only 3 different symbols but will work with most fonts and should work in a real TTY.
Note that "tty" only has half the horizontal resolution of the other two, so will show a shorter historical view.
#+begin_src conf :tangle btop.conf
graph_symbol = "braille"
#+end_src

# Graph symbol to use for graphs in cpu box, "default", "braille", "block" or "tty".
#+begin_src conf :tangle btop.conf
graph_symbol_cpu = "default"
#+end_src

# Graph symbol to use for graphs in cpu box, "default", "braille", "block" or "tty".
#+begin_src conf :tangle btop.conf
graph_symbol_mem = "default"
#+end_src

# Graph symbol to use for graphs in cpu box, "default", "braille", "block" or "tty".
#+begin_src conf :tangle btop.conf
graph_symbol_net = "default"
#+end_src

# Graph symbol to use for graphs in cpu box, "default", "braille", "block" or "tty".
#+begin_src conf :tangle btop.conf
graph_symbol_proc = "default"
#+end_src

Manually set which boxes to show. Available values are "cpu mem net proc", separate values with whitespace.
#+begin_src conf :tangle btop.conf
shown_boxes = "cpu mem net proc"
#+end_src

Update time in milliseconds, recommended 2000 ms or above for better sample times for graphs.
#+begin_src conf :tangle btop.conf
update_ms = 2000
#+end_src

Processes sorting, "pid" "program" "arguments" "threads" "user" "memory" "cpu lazy" "cpu responsive",
"cpu lazy" sorts top process over time (easier to follow), "cpu responsive" updates top process directly.
#+begin_src conf :tangle btop.conf
proc_sorting = "cpu lazy"
#+end_src

Reverse sorting order, True or False.
#+begin_src conf :tangle btop.conf
proc_reversed = False
#+end_src

Show processes as a tree.
#+begin_src conf :tangle btop.conf
proc_tree = False
#+end_src

Use the cpu graph colors in the process list.
#+begin_src conf :tangle btop.conf
proc_colors = True
#+end_src

Use a darkening gradient in the process list.
#+begin_src conf :tangle btop.conf
proc_gradient = True
#+end_src

If process cpu usage should be of the core it's running on or usage of the total available cpu power.
#+begin_src conf :tangle btop.conf
proc_per_core = False
#+end_src

Show process memory as bytes instead of percent.
#+begin_src conf :tangle btop.conf
proc_mem_bytes = True
#+end_src

Use /proc/[pid]/smaps for memory information in the process info box (very slow but more accurate)
#+begin_src conf :tangle btop.conf
proc_info_smaps = False
#+end_src

Show proc box on left side of screen instead of right.
#+begin_src conf :tangle btop.conf
proc_left = False
#+end_src

Sets the CPU stat shown in upper half of the CPU graph, "total" is always available.
Select from a list of detected attributes from the options menu.
#+begin_src conf :tangle btop.conf
cpu_graph_upper = "total"
#+end_src

Sets the CPU stat shown in lower half of the CPU graph, "total" is always available.
Select from a list of detected attributes from the options menu.
#+begin_src conf :tangle btop.conf
cpu_graph_lower = "total"
#+end_src

Toggles if the lower CPU graph should be inverted.
#+begin_src conf :tangle btop.conf
cpu_invert_lower = True
#+end_src

Set to True to completely disable the lower CPU graph.
#+begin_src conf :tangle btop.conf
cpu_single_graph = False
#+end_src

Show cpu box at bottom of screen instead of top.
#+begin_src conf :tangle btop.conf
cpu_bottom = False
#+end_src

Shows the system uptime in the CPU box.
#+begin_src conf :tangle btop.conf
show_uptime = True
#+end_src

Show cpu temperature.
#+begin_src conf :tangle btop.conf
check_temp = True
#+end_src

Which sensor to use for cpu temperature, use options menu to select from list of available sensors.
#+begin_src conf :tangle btop.conf
cpu_sensor = "Auto"
#+end_src

Show temperatures for cpu cores also if check_temp is True and sensors has been found.
#+begin_src conf :tangle btop.conf
show_coretemp = True
#+end_src

Set a custom mapping between core and coretemp, can be needed on certain cpus to get correct temperature for correct core.
Use lm-sensors or similar to see which cores are reporting temperatures on your machine.
Format "x:y" x=core with wrong temp, y=core with correct temp, use space as separator between multiple entries.
Example: "4:0 5:1 6:3"
#+begin_src conf :tangle btop.conf
cpu_core_map = ""
#+end_src

Which temperature scale to use, available values: "celsius", "fahrenheit", "kelvin" and "rankine".
#+begin_src conf :tangle btop.conf
temp_scale = "celsius"
#+end_src

Use base 10 for bits/bytes sizes, KB = 1000 instead of KiB = 1024.
#+begin_src conf :tangle btop.conf
base_10_sizes = False
#+end_src

Show CPU frequency.
#+begin_src conf :tangle btop.conf
show_cpu_freq = True
#+end_src

Draw a clock at top of screen, formatting according to strftime, empty string to disable.
Special formatting: /host = hostname | /user = username | /uptime = system uptime
#+begin_src conf :tangle btop.conf
clock_format = "%X"
#+end_src

Update main ui in background when menus are showing, set this to false if the menus is flickering too much for comfort.
#+begin_src conf :tangle btop.conf
background_update = True
#+end_src

Custom cpu model name, empty string to disable.
#+begin_src conf :tangle btop.conf
custom_cpu_name = ""
#+end_src

Optional filter for shown disks, should be full path of a mountpoint, separate multiple values with whitespace " ".
Begin line with "exclude=" to change to exclude filter, otherwise defaults to "most include" filter. Example: disks_filter="exclude=/boot /home/user".
#+begin_src conf :tangle btop.conf
disks_filter = ""
#+end_src

Show graphs instead of meters for memory values.
#+begin_src conf :tangle btop.conf
mem_graphs = True
#+end_src

Show mem box below net box instead of above.
#+begin_src conf :tangle btop.conf
mem_below_net = False
#+end_src

If swap memory should be shown in memory box.
#+begin_src conf :tangle btop.conf
show_swap = True
#+end_src

Show swap as a disk, ignores show_swap value above, inserts itself after first disk.
#+begin_src conf :tangle btop.conf
swap_disk = True
#+end_src

If mem box should be split to also show disks info.
#+begin_src conf :tangle btop.conf
show_disks = True
#+end_src

Filter out non physical disks. Set this to False to include network disks, RAM disks and similar.
#+begin_src conf :tangle btop.conf
only_physical = True
#+end_src

Read disks list from /etc/fstab. This also disables only_physical.
#+begin_src conf :tangle btop.conf
use_fstab = True
#+end_src

Toggles if io activity % (disk busy time) should be shown in regular disk usage view.
#+begin_src conf :tangle btop.conf
show_io_stat = True
#+end_src

Toggles io mode for disks, showing big graphs for disk read/write speeds.
#+begin_src conf :tangle btop.conf
io_mode = False
#+end_src

Set to True to show combined read/write io graphs in io mode.
#+begin_src conf :tangle btop.conf
io_graph_combined = False
#+end_src

Set the top speed for the io graphs in MiB/s (100 by default), use format "mountpoint:speed" separate disks with whitespace " ".
Example: "/mnt/media:100 /:20 /boot:1".
#+begin_src conf :tangle btop.conf
io_graph_speeds = ""
#+end_src

Set fixed values for network graphs in Mebibits. Is only used if net_auto is also set to False.
#+begin_src conf :tangle btop.conf
net_download = 100
net_upload = 100
#+end_src

Use network graphs auto rescaling mode, ignores any values set above and rescales down to 10 Kibibytes at the lowest.
#+begin_src conf :tangle btop.conf
net_auto = True
#+end_src

Sync the auto scaling for download and upload to whichever currently has the highest scale.
#+begin_src conf :tangle btop.conf
net_sync = False
#+end_src

Starts with the Network Interface specified here.
#+begin_src conf :tangle btop.conf
net_iface = ""
#+end_src

Show battery stats in top right if battery is present.
#+begin_src conf :tangle btop.conf
show_battery = True
#+end_src

Which battery to use if multiple are present. "Auto" for auto detection.
#+begin_src conf :tangle btop.conf
selected_battery = "Auto"
#+end_src

Set loglevel for "~/.config/btop/btop.log" levels are: "ERROR" "WARNING" "INFO" "DEBUG".
The level set includes all lower levels, i.e. "DEBUG" will show all logging info.
#+begin_src conf :tangle btop.conf
log_level = "WARNING"
#+end_src
