library: ~/.config/beets/library.db
directory: ~/music

import:
    write: yes       # -w -W
    copy: no         # -c -C
    move: yes
    resume: ask      # -p -P
    timid: no        # -t
    group_albums: no # -g
    autotag: yes     # -a
    duplicate_action: ask
    bell: yes
    languages: en ru

asciify_paths: yes
per_disc_numbering: yes

paths:
    default: '%lower{$albumartist}/%lower{$album%aunique{}}/%lower{${track}-${title}}'
    singleton: '%lower{$artist}/%lower{$title}'
    albumtype:soundtrack: 'soundtracks/%lower{$album%aunique{}}/%lower{${track}-${title}}'
    comp: 'compilations/%lower{$album%aunique{}}/%lower{${track}-${title}}'

replace:
    '[\x00-\x1f]': _
    '&': 'and'
    '[~!\\/<>"\?\*\|\[\]()]': ''
    "'": ''
    '[\.]+$': ''
    '^[\.]': ''
    '\s+$': ''
    '^\s+': ''
    '\s*[-,;:]\s*': '-'
    ' ': '-'

musicbrainz:
    searchlimit: 15

plugins: chroma fetchart info lastgenre mbsubmit mbsync mpdstats mpdupdate scrub

chroma:
    auto: yes

fetchart:
    auto: yes
    minwidth: 0
    maxwidth: 0
    quality: 0
    max_filesize: 0
    enforce_ratio: no
    cautious: no
    cover_names:
    - cover
    - front
    - art
    - album
    - folder
    sources:
    - filesystem
    - coverart
    - itunes
    - amazon
    - albumart
    store_source: no
    high_resolution: no
    deinterlace: no

lastgenre:
    auto: yes
    canonical: no
    count: 5
    fallback:
    force: yes
    min_weight: 10
    prefer_specific: no
    source: album
    whitelist: yes
    title_case: yes

lyrics:
  auto: no

mpd:
    rating: yes
    rating_mix: 0.75

scrub:
    auto: yes
