#+TITLE: Zathura
#+AUTHOR: Artem Smaznov
#+DESCRIPTION: A vim-like document viewer
#+STARTUP: overview
#+PROPERTY: header-args :tangle zathurarc

* Table of Contents :toc:
- [[#dependencies][Dependencies]]
- [[#general][General]]
- [[#theme][Theme]]
- [[#key-bindings][Key Bindings]]
  - [[#normal-mode][Normal Mode]]
  - [[#fullscreen-mode][Fullscreen Mode]]
  - [[#presentation-mode][Presentation Mode]]
  - [[#index-mode][Index Mode]]

* Dependencies
|-----------------+------------------------------|
| Name            | Description                  |
|-----------------+------------------------------|
| [[https://archlinux.org/packages/?name=zathura][zathura]]         | A vim-like document viewer   |
|-----------------+------------------------------|
| [[https://archlinux.org/packages/?name=zathura-cb][zathura-cb]]      | Comic book support           |
| [[https://archlinux.org/packages/?name=zathura-djvu][zathura-djvu]]    | DjVu support                 |
| [[https://archlinux.org/packages/?name=zathura-pdf-poppler][zathura-poppler]] | PDF support based on Poppler |
| [[https://archlinux.org/packages/?name=zathura-ps][zathura-ps]]      | PostScript support           |
|-----------------+------------------------------|

#+begin_example shell
sudo pacman -S --needed zathura zathura-cb zathura-djvu zathura-pdf-poppler zathura-ps
#+end_example

* General
Defines if the search results should be cleared on abort.
#+begin_src vimrc
set abort-clear-search true
#+end_src

Defines which auto adjustment mode should be used if a document is loaded.  Possible options are "best-fit" and "width".
#+begin_src vimrc
set adjust-open "best-fit"
#+end_src

Defines if the number of pages per row should be honored when advancing a page.
#+begin_src vimrc
set advance-pages-per-row false
#+end_src

Tells zathura whether to save document history at each page change or only when closing a document.
#+begin_src vimrc
set continuous-hist-save false
#+end_src

Defines the database backend to use for bookmarks and input history. Possible values are "plain", "sqlite"  (ifbuilt  with
sqlite support) and "null". If "null" is used, bookmarks and input history will not be stored.
#+begin_src vimrc
set database "plain"
#+end_src

En/Disables the D-Bus service. If the services is disabled, SyncTeX forward synchronization is not available.
#+begin_src vimrc
set dbus-service true
#+end_src

Defines whether zathura's window should be raised when receiving certain commands via D-Bus.
#+begin_src vimrc
set dbus-raise-window true
#+end_src

Defines the file monitor backend used to check for changes in files. Possible values are "glib", "signal" (if signal handling
is supported), and "noop". The "noop" file monitor does not trigger reloads.
#+begin_src vimrc
set filemonitor "glib"
#+end_src

En/Disables incremental search (search while typing).
#+begin_src vimrc
set incremental-search true
#+end_src

Defines the opacity of a highlighted element
#+begin_src vimrc
set highlight-transparency 0.5
#+end_src

The page padding defines the gap in pixels between each rendered page.
#+begin_src vimrc
set page-padding 3
#+end_src

Defines the maximum number of pages that could be kept in the page cache. When
the cache is full and a new  page that  isn't cached becomes visible, the least
recently viewed page in the cache will be evicted to make room for the new one.
Large values for this variable are NOT recommended, because this will lead to
consuming a significant portion of the system memory.
#+begin_src vimrc
set page-cache-size 15
#+end_src

Defines the maximum size in pixels of the thumbnail that could be kept in the
thumbnail cache  per  page. The  thumbnail is scaled  for a quick preview during
zooming before the page is rendered. When the page is rendered, the result is
saved as the thumbnail only if the size is no more than this value. A larger
value increases quality but introduces longer delay in  zooming and uses more
system memory.
#+begin_src vimrc
set page-thumbnail-size 4194304
#+end_src

Defines the number of pages that are rendered next to each other in a row.
#+begin_src vimrc
set pages-per-row 1
#+end_src

Defines  the  column  in which  the  first  page will  be  displayed.  This
setting is stored separately for every value of pages-per-row according to the
following pattern <1 page per row>:[<2 pages per row>[: ...]]. The last value in
the list will be used for all other number of pages per row if not set
explicitly.
Per  default,  the  first column is set to 2 for double-page layout, i.e. the
value is set to 1:2. A value of 1:1:3 would put the first page in dual-page
layout in the first column, and for layouts with more columns the first page
would be put in the 3rd column.
#+begin_src vimrc
set first-page-column "1:2"
#+end_src

Defines if the "Loading..." text should be displayed if a page is rendered.
#+begin_src vimrc
set render-loading true
#+end_src

Defines the horizontal step size of scrolling by calling the scroll command once
#+begin_src vimrc
set scroll-hstep -1
#+end_src

Defines the step size of scrolling by calling the scroll command once
#+begin_src vimrc
set scroll-step 40
#+end_src

Defines the proportion of the current viewing area that should be visible after scrolling a full page.
#+begin_src vimrc
set scroll-full-overlap 0
#+end_src

Defines if the last/first page should be wrapped
#+begin_src vimrc
set scroll-wrap false
#+end_src

Defines if the directories should be displayed in completion.
#+begin_src vimrc
set show-directories true
#+end_src

Defines if hidden files and directories should be displayed in completion.
#+begin_src vimrc
set show-hidden false
#+end_src

Defines the number of recent files that should be displayed in completion.  If
the value is negative, no upper bounds are applied. If the value is 0, no recent
files are shown.
#+begin_src vimrc
set show-recent 10
#+end_src

Defines if scrolling by half or full pages stops at page boundaries.
#+begin_src vimrc
set scroll-page-aware false
#+end_src

En/Disables the ability of changing zoom when following links.
#+begin_src vimrc
set link-zoom true
#+end_src

En/Disables aligning to the left internal link targets, for example from the index.
#+begin_src vimrc
set link-hadjust true
#+end_src

En/Disables horizontally centered search results.
#+begin_src vimrc
set search-hadjust true
#+end_src

Use basename of the file in the window title.
#+begin_src vimrc
set window-title-basename true
#+end_src

Display a short version of the file path, which replaces $HOME with ~, in the window title.
#+begin_src vimrc
set window-title-home-tilde false
#+end_src

Display the page number in the window title.
#+begin_src vimrc
set window-title-page false
#+end_src

Use basename of the file in the statusbar.
#+begin_src vimrc
set statusbar-basename false
#+end_src

Display a short version of the file path, which replaces $HOME with ~, in the statusbar.
#+begin_src vimrc
set statusbar-home-tilde true
#+end_src

En/Disables horizontally centered zooming.
#+begin_src vimrc
set zoom-center false
#+end_src

Center the screen at the vertical midpoint of the page by default.
#+begin_src vimrc
set vertical-center false
#+end_src

Defines the maximum percentage that the zoom level can be.
#+begin_src vimrc
set zoom-max 1000
#+end_src

Defines the minimum percentage that the zoom level can be.
#+begin_src vimrc
set zoom-min 10
#+end_src

Defines the amount of percent that is zoomed in or out on each command.
#+begin_src vimrc
set zoom-step 10
#+end_src

Defines the X clipboard into which mouse-selected data will be written.  When it
is "clipboard", selected data will be  written to the CLIPBOARD clipboard, and
can be pasted using the Ctrl+v key combination.  When it is "primary", selected
data will be written to the PRIMARY clipboard, and can be pasted using the
middle mouse button, or the Shift-Insert key combination.
#+begin_src vimrc
set selection-clipboard "clipboard"
#+end_src

Defines if a notification should be displayed after selecting text.
#+begin_src vimrc
set selection-notification true
#+end_src

En/Disables SyncTeX backward synchronization support.
#+begin_src vimrc
set synctex true
#+end_src

Defines the command executed for SyncTeX backward synchronization.
#+begin_src vimrc
set synctex-editor-command ""
#+end_src

Defines the sandbox mode to use for the seccomp syscall filter. Possible values
are "none", "normal" and "strict". If  "none" is  used, the  sandbox will be
disabled. The use of "normal" will provide minimal protection and allow normal
use of zathura with support for all features. The "strict" mode is a read only
sandbox that is intended for viewing documents only.

Some features are disabled when using strict sandbox mode:
- saving/writing files
- use of input methods like ibus
- printing
- bookmarks and history
  
No feature regressions are expected when using normal sandbox mode.
When running under WSL, the default is "none" since seccomp is not supported in that environment.
#+begin_src vimrc
set sandbox "normal"
#+end_src

Defines whether the window document should be updated based on the first page of a document.
#+begin_src vimrc
set window-icon-document false
#+end_src

Defines whether pages in multi-column view should start from the right side.
#+begin_src vimrc
set page-right-to-left false
#+end_src

* Theme
#+begin_src vimrc
set font "hack normal 12"
#+end_src

Defines the maximum number of displayed completion entries.
#+begin_src vimrc
set n-completion-items 15
#+end_src

Shows or hides GUI elements. If it contains:
- 'c' the command line is displayed
- 's' the statusbar is displayed
- 'h' the horizontal scrollbar is displayed
- 'v' the vertical scrollbar is displayed
#+begin_src vimrc
set guioptions "shv"
#+end_src

Defines the colors that is used for command line completion entries
#+begin_src vimrc
set completion-fg "#ebdbb2"
set completion-bg "#1d2021"
set completion-group-fg "#ebdbb2"
set completion-group-bg "#282828"
set completion-highlight-fg "#d5c4a1"
set completion-highlight-bg "#504945"
#+end_src

Defines the default background colors
#+begin_src vimrc
set default-fg "#ebdbb2"
set default-bg "#282828"

set inputbar-fg "#ebdbb2"
set inputbar-bg "#1d2021"

set statusbar-fg "#ebdbb2"
set statusbar-bg "#3c3836"
#+end_src

Defines the background color for a notification
#+begin_src vimrc
set notification-fg "#282828"
set notification-bg "#ebdbb2"
set notification-error-fg "#282828"
set notification-error-bg "#fb4934"
set notification-warning-fg "#282828"
set notification-warning-bg "#fabd2f"
#+end_src

Defines the color that is used for highlighting parts of the document (e.g.: show search results)
#+begin_src vimrc
set highlight-color "#fabd2f"
#+end_src

Defines the color that is used to show the current selected highlighted element (e.g: current search result)
#+begin_src vimrc
set highlight-active-color "#fe8019"
#+end_src

Defines the color that is used for text when highlighting parts of the document (e.g.: number for links).
#+begin_src vimrc
set highlight-fg "#fabd2f"
#+end_src

Defines the colors of the index mode.
#+begin_src vimrc
set index-fg "#DDDDDD"
set index-bg "#232323"
#+end_src

Defines the colors of the selected element in index mode.
#+begin_src vimrc
set index-active-fg "#232323"
set index-active-bg "#9FBC00"
#+end_src

Defines the colors used for the "Loading..." text.
#+begin_src vimrc
set render-loading-fg "#282828"
set render-loading-bg "#ebdbb2"
#+end_src

Recoloring
#+begin_src vimrc
set recolor
set recolor-keephue
set recolor-lightcolor "#282828"
set recolor-darkcolor "#ebdbb2"
set recolor-reverse-video false
#+end_src

* Key Bindings
** Normal Mode
Un-mapping
#+begin_src vimrc
unmap <Space>
unmap t
#+end_src

#+begin_src vimrc
map <C-=> zoom in
map <C--> zoom out
map <C-0> zoom

map ZZ quit

map <A-x> feedkeys :

map tc recolor
map td feedkeys d
#+end_src

** Fullscreen Mode
Un-mapping
#+begin_src vimrc
unmap [fullscreen] <Space>
#+end_src

#+begin_src vimrc
map [fullscreen] <C-=> zoom in
map [fullscreen] <C--> zoom out
map [fullscreen] <C-0> zoom

map [fullscreen] ZZ quit

map [fullscreen] <A-x> feedkeys :
#+end_src

** Presentation Mode
#+begin_src vimrc
#+end_src

** Index Mode
#+begin_src vimrc
#+end_src
