#!/usr/bin/env bash
#
# Custom cli prompt

# Git Indicators
export GIT_PS1_SHOWDIRTYSTATE=true
export GIT_PS1_SHOWSTASHSTATE=true
export GIT_PS1_SHOWUNTRACKEDFILES=true
export GIT_PS1_SHOWUPSTREAM=auto

# Define colors
gray="\033[1;30m"
red="\033[1;31m"
green="\033[1;32m"
yellow="\033[1;33m"
blue="\033[1;34m"
magenta="\033[1;35m"
cyan="\033[1;36m"
white="\033[1;37m"

lightgray="\033[0;30m"
lightred="\033[0;31m"
lightgreen="\033[0;32m"
lightyellow="\033[0;33m"
lightblue="\033[0;34m"
lightmagenta="\033[0;35m"
lightcyan="\033[0;36m"
white="\033[0;37m"

nocolor="\033[0m"

# Color bash prompt depending on user
if [[ ${EUID} == 0 ]]; then # if user is root
  prompt_color=$lightred
  directory_color=$lightcyan
else
  prompt_color=$lightgreen
  directory_color=$lightyellow
  user_display='\u@'
fi

git_color=$lightcyan

if [[ -f /usr/share/git/completion/git-prompt.sh ]]; then
  . /usr/share/git/completion/git-prompt.sh
fi

hostPart="\[${prompt_color}\]$user_display\h\[${prompt_color}\]"
workingDirectoryPart="\[${directory_color}\]\w\[${prompt_color}\]"
signPart="\[${prompt_color}\]"'\$'"\[${nocolor}\]"
gitBranchPart="\[${git_color}\]\$(__git_ps1 ' %s')\[${nocolor}\]"

PS1="$hostPart [ $workingDirectoryPart ]: $gitBranchPart\n $signPart "

