directory: ~/music
library: ~/.config/beets/library.db

import:
  copy: yes
  move: yes
  write: yes
  group_albums: no
  languages: en ru

asciify_paths: yes

paths:
  default: $albumartist/$album%aunique{}/$track - $title
  singleton: $artist/$title
  comp: compilations/$album%aunique{}/$track - $title

replace:
    '[\\/]': ''
    '^\.': _
    '[\x00-\x1f]': _
    ':': ' -'
    '[<>"\?\*\|]': ''
    '\.$': ''
    '\s+$': ''
    '^\s+': ''
    '^[-!]': ''
    '~': ''

plugins: fetchart chroma lastgenre mpdstats mpdupdate

# mpd:
#   password: ""

# chroma:
#   auto: no

musicbrainz:
  searchlimit: 10
