directory: ~/Music
library: ~/.config/beets/library.db

import:
  copy: yes
  move: yes
  write: yes
  group_albums: no
  languages: en ru

paths:
  default: $albumartist/$album%aunique{}/$track - $title
  singleton: $artist/$title
  comp: Compilations/$album%aunique{}/$track - $title

replace:
    '[\\/]': ''
    '^\.': _
    '[\x00-\x1f]': _
    ':': ' -'
    '[<>"\?\*\|]': ''
    '\.$': ''
    '\s+$': ''
    '^\s+': ''
    '^-': ''

plugins: fetchart chroma lastgenre mpdstats mpdupdate

musicbrainz:
  searchlimit: 10
