directory: ~/Music
library: ~/.config/beets/library.db

import:
  copy: yes
  move: yes
  write: yes
  group_albums: yes
  languages: en ru

paths:
    default: $albumartist/$album%aunique{}/$track - $title
    singleton: $artist/$title
    comp: Compilations/$album%aunique{}/$track - $title

plugins: fetchart chroma
