add_newline = true

[character]
success_symbol = "[➜](bold green)"

# [hostname]
# ssh_only = false

# [username]
# show_always = true

# [directory]
# truncation_length = 3
# truncate_to_repo = true
